[settings]
# Use the Node version from .nvmrc
idiomatic_version_file_enable_tools = ['node']
# Allow the use of the postinstall hook
experimental = true

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in package.json
postinstall = 'corepack enable'

[tasks.dev]
run = "make dev"
